// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowSettings():Promise<Record<string, number>>;

export function SetWindowSettings(arg1:number,arg2:number):Promise<void>;
