// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewConversation(arg1) {
  return window['go']['main']['App']['CreateNewConversation'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetAllConversations() {
  return window['go']['main']['App']['GetAllConversations']();
}

export function GetConversationHistory(arg1) {
  return window['go']['main']['App']['GetConversationHistory'](arg1);
}

export function GetWindowSettings() {
  return window['go']['main']['App']['GetWindowSettings']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetWindowSettings(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSettings'](arg1, arg2);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}
