// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWindowSettings() {
  return window['go']['main']['App']['GetWindowSettings']();
}

export function SetWindowSettings(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSettings'](arg1, arg2);
}
