// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateNewConversation(arg1:string):Promise<model.Conversation>;

export function DeleteConversation(arg1:number):Promise<void>;

export function GetAllConversations():Promise<Array<model.Conversation>>;

export function GetConversationHistory(arg1:number):Promise<Array<model.Message>>;

export function GetWindowSettings():Promise<Record<string, number>>;

export function SendMessage(arg1:number,arg2:string):Promise<model.ChatResponseDTO>;

export function SetWindowSettings(arg1:number,arg2:number):Promise<void>;

export function UpdateConversationTitle(arg1:number,arg2:string):Promise<void>;
